apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: aurora
spec:
  displayName: Aurora
  author:
    name: chuan
    website: https://github.com/pchuan98
  description: fork from https://github.com/Roozenlz/halo-theme-aurora
  logo: 
  website: https://blog.pchuan.live
  repo: https://github.com/pchuan98/aurora
  settingName: "aurora-setting"
  configMapName: "aurora-configMap"
  version: "1.0.4"
  require: ">=2.8.0"

  # 自定义模板设置
  customTemplates:
    post:
      - name: pure
        description: 纯粹的网站
        screenshot:
        file: pure.html